name: .NET Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./UserInfoManager.sln

    - name: Build
      run: dotnet build ./UserInfoManager.sln --no-restore

    - name: Run tests
      run: dotnet test ./UserInfoManager.sln --no-build --verbosity normal
